language: php
php:
  - 5.4

env:
  - DB=mysql

before_script:
  - composer require pylonworks/essencebase:dev-master --dev

script:
  - phpunit -c Packages/Application/PylonWorks.Essencebase/Tests/Unit.travis.xml
  - phpunit -c Packages/Application/PylonWorks.Essencebase/Tests/Functional.travis.xml

