language: php
php:
  - 5.4

env:
  - DB=mysql

before_script:
  - composer require typo3/buildessentials:dev-master
  - composer install --dev
  - ls -la 

script:
  - phpunit -c Tests/Unit.travis.xml

notifications:
  email:
    - development@morphodo.com
