language: php
php:
  - 5.4

env:
  - DB=mysql

before_script:
  - mkdir build-requirements
  - cd build-requirements
  - composer require typo3/buildessentials:dev-master
  - composer require mikey179/vfsStream:v1.1.*

script:
  - phpunit -c Tests/Unit.travis.xml

notifications:
  email:
    - development@morphodo.com