language: php
php:
  - 5.4

env:
  - DB=mysql

before_script:
  - rm -rf !(composer.json|.travis.yml)
  - sed -i '2,3d' composer.json
  - composer require pylonworks/essencebase:*
  - composer install --dev
  - sed -i '/Subroutes from the Welcome package/,+12d' Configuration/Routes.yaml

script:
  - phpunit -c Packages/Application/PylonWorks.Essencebase/Tests/Unit.xml
  - phpunit -c Packages/Application/PylonWorks.Essencebase/Tests/Functional.xml

