# Logout
-
  name: 'Fallback'
  uriPattern: 'logout'
  defaults:
    '@package': 'PylonWorks.Essencebase'
    '@controller': 'Login'
    '@action': 'logout'

# Dashboard
-
  name: 'Default dashboard'
  uriPattern: 'dashboard'
  defaults:
    '@package': 'PylonWorks.Essencebase'
    '@controller': 'Dashboard'
    '@action': 'index'

# User settings
-
  name: 'Default dashboard'
  uriPattern: 'user/settings/{@action}'
  defaults:
    '@package': 'PylonWorks.Essencebase'
    '@controller': 'User'
    '@action': 'index'
  appendExceedingArguments: true

# Authenticate
-
  name: 'Authenticate'
  uriPattern: 'authenticate'
  defaults:
    '@package': 'PylonWorks.Essencebase'
    '@controller': 'Login'
    '@action': 'authenticate'

# Fallback
-
  name: 'Fallback'
  uriPattern: ''
  defaults:
    '@package': 'PylonWorks.Essencebase'
    '@controller': 'Login'
    '@action': 'index'