TYPO3:
  Flow:
    configuration:
      compileConfigurationFiles: TRUE
    security:
      authentication:
        authenticationStrategy: oneToken
        providers:
          DefaultProvider:
            provider: PersistedUsernamePasswordProvider
            entryPoint: 'WebRedirect'
            entryPointOptions:
              routeValues:
                '@package': 'PylonWorks.Essencebase'
                '@controller': 'Login'
                '@action': 'authenticate'
                '@format': 'html'
PylonWorks:
  EssenceBase:
    version: '0.1'

        #  AdminInterfaceProvider:
        #    provider: 'PersistedUsernamePasswordProvider'
        #    providerOptions:
        #      fooBar: 'baz'
        #    requestPatterns:
        #      controllerObjectName: 'TYPO3\Admin\Controller\.*'
        #    entryPoint: 'WebRedirect'
        #    entryPointOptions:
        #      routeValues:
        #        '@package': 'Your.Package'
        #        '@controller': 'Authenticate'
        #        '@action': 'login'
        #        '@format': 'html'
